[package]
name = "re2dfa"
version = "1.0.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
smallvec = "0.6.9"
# it seems nom = "5" won't work
nom = "5.0.0-beta2"
bitset = { git = "https://github.com/MashPlant/bitset" }
print = { path = "src/print" }