[package]
name = "re2dfa"
version = "1.0.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
smallvec = "0.6.9"
nom = "5.0"
bitset = { git = "https://github.com/MashPlant/bitset" }
print = { path = "src/print" }

[dev-dependencies]
clap = "2.33.0"

[lib]
path = 'src/lib.rs'

[[example]]
name = 'show_fa'