[package]
name = "re2dfa"
version = "0.1.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
smallvec = "0.6.9"
# it seems nom = "5" won't work
nom = "5.0.0-beta2"
bitset = { path = "src/bitset" }
print = { path = "src/print" }

[dev-dependencies]
regex = "1"
lazy_static = "0.2.8"