[package]
name = "re2dfa-derive"
version = "0.1.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
re2dfa = { path = "../re2dfa" }
syn = { version = "0.15", features = ["extra-traits", "full"] }
proc-macro2 = "0.4"
aho-corasick = "0.7"

[lib]
proc-macro = true